# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cgross-s <cgross-s@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/07 13:24:41 by cgross-s          #+#    #+#              #
#    Updated: 2025/04/06 08:07:24 by cgross-s         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CC = cc
CFLAGS = -Wall -Wextra -Werror

SRCS =	ft_atoi.c ft_isprint.c ft_putchar_fd.c \
		ft_striteri.c ft_strnstr.c ft_putnbr.c ft_putnbr_base.c ft_putptr.c \
		ft_bzero.c ft_itoa.c ft_putendl_fd.c ft_strjoin.c ft_strrchr.c \
		ft_calloc.c ft_memchr.c ft_putnbr_fd.c ft_strlcat.c ft_strtrim.c \
		ft_isalnum.c ft_memcmp.c ft_putstr_fd.c ft_strlcpy.c ft_substr.c \
		ft_isalpha.c ft_memcpy.c ft_split.c ft_strlen.c ft_tolower.c \
		ft_isascii.c ft_memmove.c ft_strchr.c ft_strmapi.c ft_toupper.c \
		ft_isdigit.c ft_memset.c ft_strdup.c ft_strncmp.c ft_putstr.c \
		ft_putchar.c ft_atol.c ft_atof.c ft_realloc.c ft_strndup.c

OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re